"""users table

Revision ID: c8934c2da7f4
Revises: 38c4e85512a9
Create Date: 2022-01-22 18:37:39.077406

"""

# revision identifiers, used by Alembic.
revision = 'c8934c2da7f4'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
